H:
 [[1.05828881+0.j 0.        +0.j 0.        +0.j ... 0.        +0.j
  0.        +0.j 0.00316228+0.j]
 [0.        +0.j 1.00524151+0.j 0.        +0.j ... 0.        +0.j
  0.        +0.j 0.00316228+0.j]
 [0.        +0.j 0.        +0.j 1.02016914+0.j ... 0.        +0.j
  0.        +0.j 0.00316228+0.j]
 ...
 [0.        +0.j 0.        +0.j 0.        +0.j ... 1.03269148+0.j
  0.        +0.j 0.00316228+0.j]
 [0.        +0.j 0.        +0.j 0.        +0.j ... 0.        +0.j
  0.99836785+0.j 0.00316228+0.j]
 [0.00316228+0.j 0.00316228+0.j 0.00316228+0.j ... 0.00316228+0.j
  0.00316228+0.j 1.        +0.j]]
Eigs:
 [0.85213839+0.j 0.87081396+0.j 0.87246096+0.j ... 1.14898342+0.j
 1.16025421+0.j 1.1670476 +0.j]
0 of 500
Time to get coefficients: 2.176 s
Stochastic Time: 9.620 s
1 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.245 s
2 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
3 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.246 s
4 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.242 s
5 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.251 s
6 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.246 s
7 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
8 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
9 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
10 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.250 s
11 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.243 s
12 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
13 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
14 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
15 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
16 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.251 s
17 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.243 s
18 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.241 s
19 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
20 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
21 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
22 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.249 s
23 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.245 s
24 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
25 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.246 s
26 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.248 s
27 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.250 s
28 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.246 s
29 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
30 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
31 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
32 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
33 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.251 s
34 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
35 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
36 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
37 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.240 s
38 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
39 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.249 s
40 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
41 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
42 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
43 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
44 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.247 s
45 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.246 s
46 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
47 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
48 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.245 s
49 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.247 s
50 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.250 s
51 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.245 s
52 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.246 s
53 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
54 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
55 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
56 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.253 s
57 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.245 s
58 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
59 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.249 s
60 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.242 s
61 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
62 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.251 s
63 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
64 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
65 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.242 s
66 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
67 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.250 s
68 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.246 s
69 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.248 s
70 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.246 s
71 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
72 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
73 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.251 s
74 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.245 s
75 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
76 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.242 s
77 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.241 s
78 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
79 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.250 s
80 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.243 s
81 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
82 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.243 s
83 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.241 s
84 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.246 s
85 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.242 s
86 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.241 s
87 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
88 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.242 s
89 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
90 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.246 s
91 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.241 s
92 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.242 s
93 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.241 s
94 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.241 s
95 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
96 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.251 s
97 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
98 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.242 s
99 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
100 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
101 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
102 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.249 s
103 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
104 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
105 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.242 s
106 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.242 s
107 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.294 s
108 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.286 s
109 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
110 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
111 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
112 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
113 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
114 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.288 s
115 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
116 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.290 s
117 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
118 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.289 s
119 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.297 s
120 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.290 s
121 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.289 s
122 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
123 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.288 s
124 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
125 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.289 s
126 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.289 s
127 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
128 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
129 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
130 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
131 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.286 s
132 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.286 s
133 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
134 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
135 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.288 s
136 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
137 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.288 s
138 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
139 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.285 s
140 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.289 s
141 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
142 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.288 s
143 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
144 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.289 s
145 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
146 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
147 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.297 s
148 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.288 s
149 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
150 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
151 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
152 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.288 s
153 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.296 s
154 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.289 s
155 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.286 s
156 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
157 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
158 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.302 s
159 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.299 s
160 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.297 s
161 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.298 s
162 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.299 s
163 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
164 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.305 s
165 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.298 s
166 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.299 s
167 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
168 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.303 s
169 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.304 s
170 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.299 s
171 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.302 s
172 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
173 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.299 s
174 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
175 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.307 s
176 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.295 s
177 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
178 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
179 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.284 s
180 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.284 s
181 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.302 s
182 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.292 s
183 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
184 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.290 s
185 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
186 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.301 s
187 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.296 s
188 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
189 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
190 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
191 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.288 s
192 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.297 s
193 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.292 s
194 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
195 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
196 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
197 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
198 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.296 s
199 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.288 s
200 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
201 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
202 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
203 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
204 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.292 s
205 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
206 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
207 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.294 s
208 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
209 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.301 s
210 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.285 s
211 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
212 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
213 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
214 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
215 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.300 s
216 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.295 s
217 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
218 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
219 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
220 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
221 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.297 s
222 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.289 s
223 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.296 s
224 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
225 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.297 s
226 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.304 s
227 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.294 s
228 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
229 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
230 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
231 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
232 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.299 s
233 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.290 s
234 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
235 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
236 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
237 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.300 s
238 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.289 s
239 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
240 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
241 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
242 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.289 s
243 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
244 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.293 s
245 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
246 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
247 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
248 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
249 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.296 s
250 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.290 s
251 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
252 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.296 s
253 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
254 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
255 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.288 s
256 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
257 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
258 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.297 s
259 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
260 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
261 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.288 s
262 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
263 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.296 s
264 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
265 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.289 s
266 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
267 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.290 s
268 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.296 s
269 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
270 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
271 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
272 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.285 s
273 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.286 s
274 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
275 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
276 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
277 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.304 s
278 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.288 s
279 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.296 s
280 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.296 s
281 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
282 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.284 s
283 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
284 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.284 s
285 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
286 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
287 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.284 s
288 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.299 s
289 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.297 s
290 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
291 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
292 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
293 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
294 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.292 s
295 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.287 s
296 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
297 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.288 s
298 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
299 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.289 s
300 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
301 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.289 s
302 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
303 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.296 s
304 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
305 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.304 s
306 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.287 s
307 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.299 s
308 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
309 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
310 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
311 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.301 s
312 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.290 s
313 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
314 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.293 s
315 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
316 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
317 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.304 s
318 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.288 s
319 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.287 s
320 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
321 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
322 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.299 s
323 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.285 s
324 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
325 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.286 s
326 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
327 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
328 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.289 s
329 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.295 s
330 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.294 s
331 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.290 s
332 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
333 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.295 s
334 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.298 s
335 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.291 s
336 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.288 s
337 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
338 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.287 s
339 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.291 s
340 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.282 s
341 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.270 s
342 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.266 s
343 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.267 s
344 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.261 s
345 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.260 s
346 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.250 s
347 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.250 s
348 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.240 s
349 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
350 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
351 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.250 s
352 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.245 s
353 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.241 s
354 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.229 s
355 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.268 s
356 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.247 s
357 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.238 s
358 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.241 s
359 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.246 s
360 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
361 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.240 s
362 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.250 s
363 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.241 s
364 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.238 s
365 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.242 s
366 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
367 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
368 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.246 s
369 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.238 s
370 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.238 s
371 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.254 s
372 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
373 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.248 s
374 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.236 s
375 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.242 s
376 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
377 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.238 s
378 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
379 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.240 s
380 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.277 s
381 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.282 s
382 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.262 s
383 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.264 s
384 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.255 s
385 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.257 s
386 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.238 s
387 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.244 s
388 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
389 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
390 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
391 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.245 s
392 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.233 s
393 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.240 s
394 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.277 s
395 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.233 s
396 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.265 s
397 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.268 s
398 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.247 s
399 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.250 s
400 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.247 s
401 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
402 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.267 s
403 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.250 s
404 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.236 s
405 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
406 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.246 s
407 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
408 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.249 s
409 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.239 s
410 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.250 s
411 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.238 s
412 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.240 s
413 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.238 s
414 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.224 s
415 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.223 s
416 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.218 s
417 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.208 s
418 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.199 s
419 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.207 s
420 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.192 s
421 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.188 s
422 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.194 s
423 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.194 s
424 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.189 s
425 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.191 s
426 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.175 s
427 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.173 s
428 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.174 s
429 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.226 s
430 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.163 s
431 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.179 s
432 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.154 s
433 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.150 s
434 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.163 s
435 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.152 s
436 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.131 s
437 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.120 s
438 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.110 s
439 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.118 s
440 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.108 s
441 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.130 s
442 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.174 s
443 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.136 s
444 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.115 s
445 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.131 s
446 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.139 s
447 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.168 s
448 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.163 s
449 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.133 s
450 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.217 s
451 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.139 s
452 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.140 s
453 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.129 s
454 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.136 s
455 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.129 s
456 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.138 s
457 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.141 s
458 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.140 s
459 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.117 s
460 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.127 s
461 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.122 s
462 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.115 s
463 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.130 s
464 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.121 s
465 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.165 s
466 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.137 s
467 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.138 s
468 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.164 s
469 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.151 s
470 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.158 s
471 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.141 s
472 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.149 s
473 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.138 s
474 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.131 s
475 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.144 s
476 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.147 s
477 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.133 s
478 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.147 s
479 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.126 s
480 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.151 s
481 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.160 s
482 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.215 s
483 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.164 s
484 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.143 s
485 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.145 s
486 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.134 s
487 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.153 s
488 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.159 s
489 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.135 s
490 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.163 s
491 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.156 s
492 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.156 s
493 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.135 s
494 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.124 s
495 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.131 s
496 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.132 s
497 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.128 s
498 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.137 s
499 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.137 s
Total Simulation Time: 2643.612
H:
 [[1.02829885+0.j 0.        +0.j 0.        +0.j ... 0.        +0.j
  0.        +0.j 0.00316228+0.j]
 [0.        +0.j 0.97704434+0.j 0.        +0.j ... 0.        +0.j
  0.        +0.j 0.00316228+0.j]
 [0.        +0.j 0.        +0.j 1.00345254+0.j ... 0.        +0.j
  0.        +0.j 0.00316228+0.j]
 ...
 [0.        +0.j 0.        +0.j 0.        +0.j ... 1.00231874+0.j
  0.        +0.j 0.00316228+0.j]
 [0.        +0.j 0.        +0.j 0.        +0.j ... 0.        +0.j
  1.02757895+0.j 0.00316228+0.j]
 [0.00316228+0.j 0.00316228+0.j 0.00316228+0.j ... 0.00316228+0.j
  0.00316228+0.j 1.        +0.j]]
Eigs:
 [0.80417192+0.j 0.84407504+0.j 0.86806097+0.j ... 1.14618731+0.j
 1.15066419+0.j 1.15363598+0.j]
0 of 500
Time to get coefficients: 2.413 s
Stochastic Time: 9.862 s
1 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.344 s
2 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.268 s
3 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.273 s
4 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.431 s
5 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.224 s
6 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.223 s
7 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.217 s
8 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.228 s
9 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.372 s
10 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.240 s
11 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.210 s
12 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.220 s
13 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.234 s
14 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.218 s
15 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.223 s
16 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.355 s
17 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.330 s
18 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.231 s
19 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.222 s
20 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.216 s
21 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.225 s
22 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.236 s
23 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.219 s
24 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.225 s
25 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.215 s
26 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.215 s
27 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.248 s
28 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.218 s
29 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.198 s
30 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.192 s
31 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.248 s
32 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.197 s
33 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.200 s
34 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.191 s
35 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.232 s
36 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.215 s
37 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.214 s
38 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.218 s
39 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.221 s
40 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.249 s
41 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.219 s
42 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.215 s
43 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.229 s
44 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.226 s
45 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.202 s
46 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.204 s
47 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.198 s
48 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.216 s
49 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.219 s
50 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.215 s
51 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.206 s
52 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.210 s
53 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.226 s
54 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.203 s
55 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.207 s
56 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.248 s
57 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.210 s
58 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.221 s
59 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.214 s
60 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.206 s
61 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.223 s
62 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.232 s
63 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.207 s
64 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.214 s
65 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.218 s
66 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.203 s
67 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.210 s
68 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.200 s
69 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.219 s
70 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.203 s
71 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.211 s
72 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.192 s
73 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.245 s
74 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.206 s
75 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.222 s
76 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.200 s
77 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.206 s
78 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.221 s
79 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.196 s
80 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.184 s
81 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.171 s
82 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.186 s
83 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.193 s
84 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.198 s
85 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.203 s
86 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.191 s
87 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.192 s
88 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.180 s
89 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.180 s
90 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.227 s
91 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.199 s
92 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.173 s
93 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.192 s
94 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.191 s
95 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.186 s
96 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.231 s
97 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.245 s
98 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.196 s
99 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.221 s
100 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.196 s
101 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.484 s
102 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.287 s
103 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.206 s
104 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.192 s
105 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.209 s
106 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.190 s
107 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.239 s
108 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.252 s
109 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.233 s
110 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.226 s
111 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.231 s
112 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.220 s
113 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.246 s
114 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.221 s
115 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.243 s
116 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.225 s
117 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.255 s
118 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.230 s
119 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.254 s
120 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.238 s
121 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.236 s
122 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.235 s
123 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.240 s
124 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.473 s
125 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.267 s
126 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.243 s
127 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.224 s
128 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.229 s
129 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.226 s
130 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.250 s
131 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.234 s
132 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.327 s
133 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.258 s
134 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.268 s
135 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.282 s
136 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.291 s
137 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.286 s
138 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.271 s
139 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.268 s
140 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.270 s
141 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.288 s
142 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.342 s
143 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.257 s
144 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.266 s
145 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.281 s
146 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.265 s
147 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.273 s
148 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.274 s
149 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.267 s
150 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.279 s
151 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.257 s
152 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.257 s
153 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.392 s
154 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.285 s
155 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.281 s
156 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.283 s
157 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.243 s
158 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.270 s
159 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.283 s
160 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.272 s
161 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.279 s
162 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.281 s
163 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.241 s
164 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.280 s
165 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.356 s
166 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.239 s
167 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.240 s
168 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
169 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.242 s
170 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.322 s
171 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.228 s
172 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.234 s
173 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.247 s
174 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.222 s
175 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.227 s
176 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.254 s
177 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.235 s
178 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.241 s
179 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
180 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.225 s
181 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.228 s
182 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.264 s
183 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.235 s
184 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.242 s
185 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.237 s
186 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.242 s
187 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.250 s
188 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.236 s
189 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.257 s
190 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.248 s
191 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
192 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.249 s
193 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.259 s
194 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.242 s
195 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.236 s
196 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.247 s
197 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.224 s
198 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.247 s
199 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.245 s
200 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
201 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.249 s
202 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.272 s
203 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.235 s
204 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.308 s
205 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.250 s
206 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.438 s
207 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.422 s
208 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.563 s
209 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.597 s
210 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.187 s
211 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.177 s
212 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.168 s
213 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.383 s
214 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.521 s
215 of 500
Time to get coefficients: 0.019 s
Stochastic Time: 5.635 s
216 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.391 s
217 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.258 s
218 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.372 s
219 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.225 s
220 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.233 s
221 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.227 s
222 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.183 s
223 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.384 s
224 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.331 s
225 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.358 s
226 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.506 s
227 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.634 s
228 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.361 s
229 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.431 s
230 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.495 s
231 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.462 s
232 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.623 s
233 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.522 s
234 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.335 s
235 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.320 s
236 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.378 s
237 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.448 s
238 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.325 s
239 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.363 s
240 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.272 s
241 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.284 s
242 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.279 s
243 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.290 s
244 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.750 s
245 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.556 s
246 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.552 s
247 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.270 s
248 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.286 s
249 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.276 s
250 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.270 s
251 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.259 s
252 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.237 s
253 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.233 s
254 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.231 s
255 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.252 s
256 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.219 s
257 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.251 s
258 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.240 s
259 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.233 s
260 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.264 s
261 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.356 s
262 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.281 s
263 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.264 s
264 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.233 s
265 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.232 s
266 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.305 s
267 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.240 s
268 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
269 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.228 s
270 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.244 s
271 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.231 s
272 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.250 s
273 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.221 s
274 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.238 s
275 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.243 s
276 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.238 s
277 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.247 s
278 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.234 s
279 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.229 s
280 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.228 s
281 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.236 s
282 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.231 s
283 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.267 s
284 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.243 s
285 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.233 s
286 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.251 s
287 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.229 s
288 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.255 s
289 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.250 s
290 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.270 s
291 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.276 s
292 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.221 s
293 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.255 s
294 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.252 s
295 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.241 s
296 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.297 s
297 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.247 s
298 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.254 s
299 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.242 s
300 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.243 s
301 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.232 s
302 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.230 s
303 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.240 s
304 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.230 s
305 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.235 s
306 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.271 s
307 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.237 s
308 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.238 s
309 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.248 s
310 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.232 s
311 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.242 s
312 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.422 s
313 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.281 s
314 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.222 s
315 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.229 s
316 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.243 s
317 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.246 s
318 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.219 s
319 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.216 s
320 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.226 s
321 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.215 s
322 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.217 s
323 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.223 s
324 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.206 s
325 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.203 s
326 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.217 s
327 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.217 s
328 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.205 s
329 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.229 s
330 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.209 s
331 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.211 s
332 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.209 s
333 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.205 s
334 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.220 s
335 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.221 s
336 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.208 s
337 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.210 s
338 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.207 s
339 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.202 s
340 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.245 s
341 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.169 s
342 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.187 s
343 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.186 s
344 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.217 s
345 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.177 s
346 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.191 s
347 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.168 s
348 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.166 s
349 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.167 s
350 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.192 s
351 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.155 s
352 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.212 s
353 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.413 s
354 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.467 s
355 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.435 s
356 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.548 s
357 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.740 s
358 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.810 s
359 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.566 s
360 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.202 s
361 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.214 s
362 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.222 s
363 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.299 s
364 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.225 s
365 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.204 s
366 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.189 s
367 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.178 s
368 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.206 s
369 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.209 s
370 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.194 s
371 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.196 s
372 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.236 s
373 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.186 s
374 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.210 s
375 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.181 s
376 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.198 s
377 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.191 s
378 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.185 s
379 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.184 s
380 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.231 s
381 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.180 s
382 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.193 s
383 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.192 s
384 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.185 s
385 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.184 s
386 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.192 s
387 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.160 s
388 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.367 s
389 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.665 s
390 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.329 s
391 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.758 s
392 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.447 s
393 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.412 s
394 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.522 s
395 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.576 s
396 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.236 s
397 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.300 s
398 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.259 s
399 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.665 s
400 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.246 s
401 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.212 s
402 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.261 s
403 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.666 s
404 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.793 s
405 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.297 s
406 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.228 s
407 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.450 s
408 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.469 s
409 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.776 s
410 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.453 s
411 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.324 s
412 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.238 s
413 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.246 s
414 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.229 s
415 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.230 s
416 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.258 s
417 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.187 s
418 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.186 s
419 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.200 s
420 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.201 s
421 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.187 s
422 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.182 s
423 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.175 s
424 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.193 s
425 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.222 s
426 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.192 s
427 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.170 s
428 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.191 s
429 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.192 s
430 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.177 s
431 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.208 s
432 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.203 s
433 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.176 s
434 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.175 s
435 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.174 s
436 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.205 s
437 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.176 s
438 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.144 s
439 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.148 s
440 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.176 s
441 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.163 s
442 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.186 s
443 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.125 s
444 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.138 s
445 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.158 s
446 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.157 s
447 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.183 s
448 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.179 s
449 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.160 s
450 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.155 s
451 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.195 s
452 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.205 s
453 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.160 s
454 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.266 s
455 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.165 s
456 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.152 s
457 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.185 s
458 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.264 s
459 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.204 s
460 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.202 s
461 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.188 s
462 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.187 s
463 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.185 s
464 of 500
Time to get coefficients: 0.018 s
Stochastic Time: 5.197 s
465 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.229 s
466 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.200 s
467 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.173 s
468 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.208 s
469 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.220 s
470 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.196 s
471 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.216 s
472 of 500
Time to get coefficients: 0.017 s
Stochastic Time: 5.277 s
473 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.195 s
474 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.167 s
475 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.169 s
476 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.182 s
477 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.186 s
478 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.178 s
479 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.212 s
480 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.226 s
481 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.191 s
482 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.189 s
483 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.234 s
484 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.186 s
485 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.195 s
486 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.148 s
487 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.147 s
488 of 500
Time to get coefficients: 0.015 s
Stochastic Time: 5.177 s
489 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.216 s
490 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.144 s
491 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.152 s
492 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.177 s
493 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.155 s
494 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.174 s
495 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.144 s
496 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.179 s
497 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.183 s
498 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.185 s
499 of 500
Time to get coefficients: 0.016 s
Stochastic Time: 5.159 s
Total Simulation Time: 2646.216
