[0.         0.62930692 0.64052807 ... 1.27663327 1.2979645  1.32893772]
0 of 200
Time to get coefficients: 1.529 s
Stochastic Time: 2.401 s
1 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
2 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.178 s
3 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
4 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
5 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.179 s
6 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
7 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
8 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
9 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
10 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
11 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
12 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
13 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
14 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
15 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
16 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
17 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
18 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
19 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.179 s
20 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
21 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
22 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
23 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
24 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.178 s
25 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
26 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
27 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
28 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
29 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
30 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
31 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
32 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
33 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
34 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
35 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
36 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
37 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
38 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
39 of 200
Time to get coefficients: 0.008 s
Stochastic Time: 0.174 s
40 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
41 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
42 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
43 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
44 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
45 of 200
Time to get coefficients: 0.004 s
Stochastic Time: 0.175 s
46 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
47 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.180 s
48 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
49 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
50 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
51 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
52 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
53 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
54 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
55 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
56 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
57 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
58 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
59 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
60 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
61 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
62 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.171 s
63 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
64 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
65 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
66 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
67 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
68 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
69 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
70 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
71 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
72 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
73 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
74 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
75 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
76 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
77 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
78 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
79 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.171 s
80 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
81 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
82 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
83 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
84 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
85 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
86 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
87 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
88 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
89 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
90 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
91 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
92 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
93 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
94 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
95 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
96 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
97 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
98 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
99 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.178 s
100 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
101 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
102 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
103 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
104 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.178 s
105 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
106 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
107 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.184 s
108 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
109 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
110 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
111 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
112 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
113 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
114 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.178 s
115 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
116 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
117 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
118 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
119 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
120 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
121 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
122 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
123 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
124 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
125 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
126 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
127 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
128 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
129 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.179 s
130 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
131 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.179 s
132 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
133 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
134 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
135 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
136 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
137 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
138 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
139 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
140 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
141 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
142 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
143 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
144 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
145 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.172 s
146 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
147 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
148 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
149 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
150 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
151 of 200
Time to get coefficients: 0.005 s
Stochastic Time: 0.175 s
152 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
153 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
154 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
155 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
156 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
157 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
158 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
159 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
160 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
161 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
162 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
163 of 200
Time to get coefficients: 0.006 s
Stochastic Time: 0.177 s
164 of 200
Time to get coefficients: 0.004 s
Stochastic Time: 0.176 s
165 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
166 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
167 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
168 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
169 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
170 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
171 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
172 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
173 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
174 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
175 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
176 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
177 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.174 s
178 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.179 s
179 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.177 s
180 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
181 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
182 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
183 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
184 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.179 s
185 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.173 s
186 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
187 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
188 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
189 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
190 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
191 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.178 s
192 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
193 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
194 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
195 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
196 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.176 s
197 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
198 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
199 of 200
Time to get coefficients: 0.007 s
Stochastic Time: 0.175 s
