[0.  0.8 1.  ... 1.  1.  1.2]
0 of 400
Time to get coefficients: 1.933 s
Stochastic Time: 2.397 s
1 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.552 s
2 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.555 s
3 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.553 s
4 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
5 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
6 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.567 s
7 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
8 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.559 s
9 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.557 s
10 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.560 s
11 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.563 s
12 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.557 s
13 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.559 s
14 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.560 s
15 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.560 s
16 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.556 s
17 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.551 s
18 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
19 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.548 s
20 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.552 s
21 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.556 s
22 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.550 s
23 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.552 s
24 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.557 s
25 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.555 s
26 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.552 s
27 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.554 s
28 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.552 s
29 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
30 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.555 s
31 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.558 s
32 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.551 s
33 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.555 s
34 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
35 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
36 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
37 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.556 s
38 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.552 s
39 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.554 s
40 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.556 s
41 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.551 s
42 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.554 s
43 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.548 s
44 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.559 s
45 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.557 s
46 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
47 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.550 s
48 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
49 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.552 s
50 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.555 s
51 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.551 s
52 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.552 s
53 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.550 s
54 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.555 s
55 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.552 s
56 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.554 s
57 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.554 s
58 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.557 s
59 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.554 s
60 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.555 s
61 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.555 s
62 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.556 s
63 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
64 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.553 s
65 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.552 s
66 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.559 s
67 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.555 s
68 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
69 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
70 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
71 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
72 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
73 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
74 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
75 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
76 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
77 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
78 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
79 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
80 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
81 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
82 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
83 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
84 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
85 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
86 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.562 s
87 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
88 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.559 s
89 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
90 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
91 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
92 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
93 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
94 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
95 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
96 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
97 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.563 s
98 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.558 s
99 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
100 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
101 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
102 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
103 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.551 s
104 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
105 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
106 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
107 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
108 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
109 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
110 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
111 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
112 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
113 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
114 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
115 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
116 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
117 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
118 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
119 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
120 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
121 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
122 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
123 of 400
Time to get coefficients: 0.007 s
Stochastic Time: 0.562 s
124 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
125 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
126 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
127 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
128 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
129 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
130 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
131 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
132 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
133 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
134 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
135 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
136 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
137 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.561 s
138 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
139 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
140 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.562 s
141 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
142 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
143 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.554 s
144 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
145 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
146 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
147 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
148 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
149 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.561 s
150 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.566 s
151 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.568 s
152 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.561 s
153 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.561 s
154 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
155 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
156 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.561 s
157 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.562 s
158 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
159 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
160 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
161 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
162 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
163 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
164 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
165 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.562 s
166 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.561 s
167 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
168 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.561 s
169 of 400
Time to get coefficients: 0.007 s
Stochastic Time: 0.561 s
170 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
171 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.558 s
172 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
173 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
174 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
175 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
176 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
177 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
178 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
179 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
180 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
181 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
182 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.562 s
183 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.557 s
184 of 400
Time to get coefficients: 0.009 s
Stochastic Time: 0.557 s
185 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
186 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
187 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.562 s
188 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
189 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
190 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
191 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
192 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
193 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
194 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
195 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
196 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
197 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
198 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.563 s
199 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
200 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
201 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
202 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
203 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
204 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.563 s
205 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.560 s
206 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.559 s
207 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
208 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
209 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
210 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
211 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
212 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.562 s
213 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
214 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
215 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.562 s
216 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
217 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.563 s
218 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.565 s
219 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
220 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
221 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
222 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.561 s
223 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.561 s
224 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.561 s
225 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
226 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
227 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.561 s
228 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
229 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
230 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
231 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
232 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
233 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
234 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
235 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
236 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
237 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
238 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
239 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
240 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
241 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
242 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
243 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
244 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
245 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
246 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
247 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
248 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
249 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
250 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
251 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
252 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
253 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
254 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.553 s
255 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
256 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
257 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.567 s
258 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
259 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
260 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
261 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
262 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.556 s
263 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.557 s
264 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.562 s
265 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
266 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.558 s
267 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.560 s
268 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.561 s
269 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.559 s
270 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
271 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
272 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
273 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.561 s
274 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
275 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
276 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
277 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
278 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
279 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
280 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
281 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
282 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.562 s
283 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
284 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.550 s
285 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
286 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
287 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
288 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
289 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
290 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
291 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
292 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
293 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
294 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
295 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
296 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
297 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
298 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
299 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
300 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
301 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
302 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
303 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
304 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
305 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
306 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
307 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
308 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
309 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
310 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.564 s
311 of 400
Time to get coefficients: 0.010 s
Stochastic Time: 0.555 s
312 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.558 s
313 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
314 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
315 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
316 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
317 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
318 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
319 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
320 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.551 s
321 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.550 s
322 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
323 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
324 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
325 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
326 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.562 s
327 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
328 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
329 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
330 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.551 s
331 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
332 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
333 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
334 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
335 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
336 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.550 s
337 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
338 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
339 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
340 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
341 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
342 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
343 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
344 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
345 of 400
Time to get coefficients: 0.006 s
Stochastic Time: 0.554 s
346 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
347 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
348 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.551 s
349 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
350 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
351 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
352 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
353 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.551 s
354 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
355 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
356 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
357 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
358 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
359 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
360 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
361 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
362 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
363 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
364 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.566 s
365 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
366 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
367 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
368 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
369 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.550 s
370 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
371 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.551 s
372 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
373 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
374 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.554 s
375 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
376 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
377 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.550 s
378 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.551 s
379 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
380 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
381 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.549 s
382 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
383 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
384 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
385 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
386 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.553 s
387 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
388 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
389 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.557 s
390 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.560 s
391 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.559 s
392 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
393 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.550 s
394 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
395 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.555 s
396 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
397 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
398 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.556 s
399 of 400
Time to get coefficients: 0.005 s
Stochastic Time: 0.552 s
Matrix too large for exact solution. 0.800 GB > 10 GB
0 of 400
1 of 400
2 of 400
3 of 400
4 of 400
5 of 400
6 of 400
7 of 400
8 of 400
9 of 400
10 of 400
11 of 400
12 of 400
13 of 400
14 of 400
15 of 400
16 of 400
17 of 400
18 of 400
19 of 400
20 of 400
21 of 400
22 of 400
23 of 400
24 of 400
25 of 400
26 of 400
27 of 400
28 of 400
29 of 400
30 of 400
31 of 400
32 of 400
33 of 400
34 of 400
35 of 400
36 of 400
37 of 400
38 of 400
39 of 400
40 of 400
41 of 400
42 of 400
43 of 400
44 of 400
45 of 400
46 of 400
47 of 400
48 of 400
49 of 400
50 of 400
51 of 400
52 of 400
53 of 400
54 of 400
55 of 400
56 of 400
57 of 400
58 of 400
59 of 400
60 of 400
61 of 400
62 of 400
63 of 400
64 of 400
65 of 400
66 of 400
67 of 400
68 of 400
69 of 400
70 of 400
71 of 400
72 of 400
73 of 400
74 of 400
75 of 400
76 of 400
77 of 400
78 of 400
79 of 400
80 of 400
81 of 400
82 of 400
83 of 400
84 of 400
85 of 400
86 of 400
87 of 400
88 of 400
89 of 400
90 of 400
91 of 400
92 of 400
93 of 400
94 of 400
95 of 400
96 of 400
97 of 400
98 of 400
99 of 400
100 of 400
101 of 400
102 of 400
103 of 400
104 of 400
105 of 400
106 of 400
107 of 400
108 of 400
109 of 400
110 of 400
111 of 400
112 of 400
113 of 400
114 of 400
115 of 400
116 of 400
117 of 400
118 of 400
119 of 400
120 of 400
121 of 400
122 of 400
123 of 400
124 of 400
125 of 400
126 of 400
127 of 400
128 of 400
129 of 400
130 of 400
131 of 400
132 of 400
133 of 400
134 of 400
135 of 400
136 of 400
137 of 400
138 of 400
139 of 400
140 of 400
141 of 400
142 of 400
143 of 400
144 of 400
145 of 400
146 of 400
147 of 400
148 of 400
149 of 400
150 of 400
151 of 400
152 of 400
153 of 400
154 of 400
155 of 400
156 of 400
157 of 400
158 of 400
159 of 400
160 of 400
161 of 400
162 of 400
163 of 400
164 of 400
165 of 400
166 of 400
167 of 400
168 of 400
169 of 400
170 of 400
171 of 400
172 of 400
173 of 400
174 of 400
175 of 400
176 of 400
177 of 400
178 of 400
179 of 400
180 of 400
181 of 400
182 of 400
183 of 400
184 of 400
185 of 400
186 of 400
187 of 400
188 of 400
189 of 400
190 of 400
191 of 400
192 of 400
193 of 400
194 of 400
195 of 400
196 of 400
197 of 400
198 of 400
199 of 400
200 of 400
201 of 400
202 of 400
203 of 400
204 of 400
205 of 400
206 of 400
207 of 400
208 of 400
209 of 400
210 of 400
211 of 400
212 of 400
213 of 400
214 of 400
215 of 400
216 of 400
217 of 400
218 of 400
219 of 400
220 of 400
221 of 400
222 of 400
223 of 400
224 of 400
225 of 400
226 of 400
227 of 400
228 of 400
229 of 400
230 of 400
231 of 400
232 of 400
233 of 400
234 of 400
235 of 400
236 of 400
237 of 400
238 of 400
239 of 400
240 of 400
241 of 400
242 of 400
243 of 400
244 of 400
245 of 400
246 of 400
247 of 400
248 of 400
249 of 400
250 of 400
251 of 400
252 of 400
253 of 400
254 of 400
255 of 400
256 of 400
257 of 400
258 of 400
259 of 400
260 of 400
261 of 400
262 of 400
263 of 400
264 of 400
265 of 400
266 of 400
267 of 400
268 of 400
269 of 400
270 of 400
271 of 400
272 of 400
273 of 400
274 of 400
275 of 400
276 of 400
277 of 400
278 of 400
279 of 400
280 of 400
281 of 400
282 of 400
283 of 400
284 of 400
285 of 400
286 of 400
287 of 400
288 of 400
289 of 400
290 of 400
291 of 400
292 of 400
293 of 400
294 of 400
295 of 400
296 of 400
297 of 400
298 of 400
299 of 400
300 of 400
301 of 400
302 of 400
303 of 400
304 of 400
305 of 400
306 of 400
307 of 400
308 of 400
309 of 400
310 of 400
311 of 400
312 of 400
313 of 400
314 of 400
315 of 400
316 of 400
317 of 400
318 of 400
319 of 400
320 of 400
321 of 400
322 of 400
323 of 400
324 of 400
325 of 400
326 of 400
327 of 400
328 of 400
329 of 400
330 of 400
331 of 400
332 of 400
333 of 400
334 of 400
335 of 400
336 of 400
337 of 400
338 of 400
339 of 400
340 of 400
341 of 400
342 of 400
343 of 400
344 of 400
345 of 400
346 of 400
347 of 400
348 of 400
349 of 400
350 of 400
351 of 400
352 of 400
353 of 400
354 of 400
355 of 400
356 of 400
357 of 400
358 of 400
359 of 400
360 of 400
361 of 400
362 of 400
363 of 400
364 of 400
365 of 400
366 of 400
367 of 400
368 of 400
369 of 400
370 of 400
371 of 400
372 of 400
373 of 400
374 of 400
375 of 400
376 of 400
377 of 400
378 of 400
379 of 400
380 of 400
381 of 400
382 of 400
383 of 400
384 of 400
385 of 400
386 of 400
387 of 400
388 of 400
389 of 400
390 of 400
391 of 400
392 of 400
393 of 400
394 of 400
395 of 400
396 of 400
397 of 400
398 of 400
399 of 400
