Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 20847.632
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21120.395
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21157.402
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 20916.283
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21263.015
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21267.329
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21284.046
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21317.046
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21344.731
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21078.657
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21082.581
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21138.274
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21461.071
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21156.321
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21181.117
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21205.435
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21232.182
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21240.009
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 20932.090
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21044.275
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21064.148
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21107.219
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21157.765
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21194.717
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21206.241
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 20854.961
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 20874.485
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21228.131
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 20914.513
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 20944.682
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21005.755
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21382.465
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21069.421
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21091.751
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21167.216
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21204.167
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21107.733
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21255.580
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21373.317
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21443.772
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21498.885
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 21526.288
