Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 33233.475
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 33338.184
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 33326.544
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 34028.494
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 33663.901
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 32728.263
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 33009.591
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 33190.094
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 34450.478
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 33507.194
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 33558.246
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 33607.168
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 37253.632
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 37296.974
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 37335.982
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 37927.343
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 37958.942
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 38026.450
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 37705.199
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 37714.730
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 37813.214
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 38082.478
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 38099.532
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 38506.989
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 85402.727
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 85435.472
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 85516.160
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 85566.948
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 86623.117
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 86768.480
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 86977.259
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 86993.471
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 87026.505
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 87161.257
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 87280.954
Matrix too large for exact solution. 0.800 GB > 10 GB
Total Simulation Time: 87662.970
