Traceback (most recent call last):
  File "stochastic_Aggregate.py", line 282, in <module>
    main()
  File "stochastic_Aggregate.py", line 270, in main
    get_Globals()
  File "stochastic_Aggregate.py", line 26, in get_Globals
    SIGG      = float(sys.argv[6]) # Coupling disorder (width / dipole scaling), 0 < SIGG < 1 
IndexError: list index out of range
Traceback (most recent call last):
  File "stochastic_Aggregate.py", line 282, in <module>
    main()
  File "stochastic_Aggregate.py", line 270, in main
    get_Globals()
  File "stochastic_Aggregate.py", line 26, in get_Globals
    SIGG      = float(sys.argv[6]) # Coupling disorder (width / dipole scaling), 0 < SIGG < 1 
IndexError: list index out of range
Traceback (most recent call last):
  File "stochastic_Aggregate.py", line 282, in <module>
    main()
  File "stochastic_Aggregate.py", line 270, in main
    get_Globals()
  File "stochastic_Aggregate.py", line 26, in get_Globals
    SIGG      = float(sys.argv[6]) # Coupling disorder (width / dipole scaling), 0 < SIGG < 1 
IndexError: list index out of range
Traceback (most recent call last):
  File "stochastic_Aggregate.py", line 282, in <module>
    main()
  File "stochastic_Aggregate.py", line 270, in main
    get_Globals()
  File "stochastic_Aggregate.py", line 26, in get_Globals
    SIGG      = float(sys.argv[6]) # Coupling disorder (width / dipole scaling), 0 < SIGG < 1 
IndexError: list index out of range
Traceback (most recent call last):
  File "stochastic_Aggregate.py", line 282, in <module>
    main()
  File "stochastic_Aggregate.py", line 270, in main
    get_Globals()
  File "stochastic_Aggregate.py", line 26, in get_Globals
    SIGG      = float(sys.argv[6]) # Coupling disorder (width / dipole scaling), 0 < SIGG < 1 
IndexError: list index out of range
Traceback (most recent call last):
  File "stochastic_Aggregate.py", line 282, in <module>
    main()
  File "stochastic_Aggregate.py", line 270, in main
    get_Globals()
  File "stochastic_Aggregate.py", line 26, in get_Globals
    SIGG      = float(sys.argv[6]) # Coupling disorder (width / dipole scaling), 0 < SIGG < 1 
IndexError: list index out of range
