/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[5.72000239e-02+0.j 1.04000407e-03+0.j 1.04000407e-03+0.j ...
  1.04000407e-03+0.j 1.04000407e-03+0.j 8.22195406e-02+0.j]
 [1.04000407e-03+0.j 1.05720002e+00+0.j 1.04000000e-04+0.j ...
  1.04000000e-04+0.j 1.04000000e-04+0.j 8.22192192e-03+0.j]
 [1.04000407e-03+0.j 1.04000000e-04+0.j 1.05720002e+00+0.j ...
  1.04000000e-04+0.j 1.04000000e-04+0.j 8.22192192e-03+0.j]
 ...
 [1.04000407e-03+0.j 1.04000000e-04+0.j 1.04000000e-04+0.j ...
  1.05720002e+00+0.j 1.04000000e-04+0.j 8.22192192e-03+0.j]
 [1.04000407e-03+0.j 1.04000000e-04+0.j 1.04000000e-04+0.j ...
  1.04000000e-04+0.j 1.05720002e+00+0.j 8.22192192e-03+0.j]
 [8.22195406e-02+0.j 8.22192192e-03+0.j 8.22192192e-03+0.j ...
  8.22192192e-03+0.j 8.22192192e-03+0.j 1.35720002e+00+0.j]]
Eigs:
 [0.05176382-1.39916219e-33j 0.98168823-5.03737527e-31j
 1.05709602+3.90312782e-18j ... 1.05709602-6.93889390e-17j
 1.05709602-9.75781955e-19j 1.54204402+1.07624748e-31j]
0 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 12.617 s
1 of 100
Time to get coefficients: 0.175 s
Stochastic Time: 4.690 s
2 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.718 s
3 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.676 s
4 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.662 s
5 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.668 s
6 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.669 s
7 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.682 s
8 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.684 s
9 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.684 s
10 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.670 s
11 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.682 s
12 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.685 s
13 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.684 s
14 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.693 s
15 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.666 s
16 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.689 s
17 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.700 s
18 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.694 s
19 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.680 s
20 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.710 s
21 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.689 s
22 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.695 s
23 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.705 s
24 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.689 s
25 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.689 s
26 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.731 s
27 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.686 s
28 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.695 s
29 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.685 s
30 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.699 s
31 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.767 s
32 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.703 s
33 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.678 s
34 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.658 s
35 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.650 s
36 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.668 s
37 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.669 s
38 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.671 s
39 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.646 s
40 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.677 s
41 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.672 s
42 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.688 s
43 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.659 s
44 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.633 s
45 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.622 s
46 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.662 s
47 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.645 s
48 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.634 s
49 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.634 s
50 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.611 s
51 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.630 s
52 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.621 s
53 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.639 s
54 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.614 s
55 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.628 s
56 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.625 s
57 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.658 s
58 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.632 s
59 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.619 s
60 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.620 s
61 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.612 s
62 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.590 s
63 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.624 s
64 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.601 s
65 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.586 s
66 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.573 s
67 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.583 s
68 of 100
Time to get coefficients: 0.164 s
Stochastic Time: 4.539 s
69 of 100
Time to get coefficients: 0.165 s
Stochastic Time: 4.615 s
70 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.593 s
71 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.605 s
72 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.643 s
73 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.634 s
74 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.591 s
75 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.633 s
76 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.587 s
77 of 100
Time to get coefficients: 0.164 s
Stochastic Time: 4.546 s
78 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.565 s
79 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.576 s
80 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.602 s
81 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.593 s
82 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.614 s
83 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.611 s
84 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.626 s
85 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.613 s
86 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.651 s
87 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.606 s
88 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.613 s
89 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.611 s
90 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.616 s
91 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.585 s
92 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.627 s
93 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.630 s
94 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.630 s
95 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.613 s
96 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.625 s
97 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.617 s
98 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.602 s
99 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.611 s
Total Simulation Time: 490.353
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[5.94000248e-02+0.j 1.08000422e-03+0.j 1.08000422e-03+0.j ...
  1.08000422e-03+0.j 1.08000422e-03+0.j 8.53818307e-02+0.j]
 [1.08000422e-03+0.j 1.05940002e+00+0.j 1.08000000e-04+0.j ...
  1.08000000e-04+0.j 1.08000000e-04+0.j 8.53814968e-03+0.j]
 [1.08000422e-03+0.j 1.08000000e-04+0.j 1.05940002e+00+0.j ...
  1.08000000e-04+0.j 1.08000000e-04+0.j 8.53814968e-03+0.j]
 ...
 [1.08000422e-03+0.j 1.08000000e-04+0.j 1.08000000e-04+0.j ...
  1.05940002e+00+0.j 1.08000000e-04+0.j 8.53814968e-03+0.j]
 [1.08000422e-03+0.j 1.08000000e-04+0.j 1.08000000e-04+0.j ...
  1.08000000e-04+0.j 1.05940002e+00+0.j 8.53814968e-03+0.j]
 [8.53818307e-02+0.j 8.53814968e-03+0.j 8.53814968e-03+0.j ...
  8.53814968e-03+0.j 8.53814968e-03+0.j 1.40940002e+00+0.j]]
Eigs:
 [0.05374505+0.00000000e+00j 0.992783  +0.00000000e+00j
 1.05929202+0.00000000e+00j ... 1.05929202-3.46944695e-18j
 1.05929202+0.00000000e+00j 1.58956402+0.00000000e+00j]
0 of 100
Time to get coefficients: 0.175 s
Stochastic Time: 12.682 s
1 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.729 s
2 of 100
Time to get coefficients: 0.176 s
Stochastic Time: 4.757 s
3 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.714 s
4 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.698 s
5 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.711 s
6 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.714 s
7 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.737 s
8 of 100
Time to get coefficients: 0.176 s
Stochastic Time: 4.708 s
9 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.727 s
10 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.719 s
11 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.726 s
12 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.726 s
13 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.729 s
14 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.722 s
15 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.706 s
16 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.723 s
17 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.725 s
18 of 100
Time to get coefficients: 0.176 s
Stochastic Time: 4.720 s
19 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.706 s
20 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.742 s
21 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.733 s
22 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.716 s
23 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.721 s
24 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.729 s
25 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.718 s
26 of 100
Time to get coefficients: 0.175 s
Stochastic Time: 4.751 s
27 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.722 s
28 of 100
Time to get coefficients: 0.176 s
Stochastic Time: 4.715 s
29 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.718 s
30 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.739 s
31 of 100
Time to get coefficients: 0.175 s
Stochastic Time: 4.791 s
32 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.748 s
33 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.722 s
34 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.707 s
35 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.708 s
36 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.721 s
37 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.710 s
38 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.708 s
39 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.674 s
40 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.685 s
41 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.687 s
42 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.685 s
43 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.662 s
44 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.661 s
45 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.652 s
46 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.676 s
47 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.643 s
48 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.664 s
49 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.651 s
50 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.647 s
51 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.636 s
52 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.663 s
53 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.658 s
54 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.633 s
55 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.658 s
56 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.655 s
57 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.649 s
58 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.647 s
59 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.646 s
60 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.626 s
61 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.617 s
62 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.610 s
63 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.647 s
64 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.611 s
65 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.613 s
66 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.590 s
67 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.580 s
68 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.595 s
69 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.636 s
70 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.612 s
71 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.617 s
72 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.611 s
73 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.610 s
74 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.575 s
75 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.582 s
76 of 100
Time to get coefficients: 0.176 s
Stochastic Time: 4.575 s
77 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.563 s
78 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.569 s
79 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.599 s
80 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.601 s
81 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.604 s
82 of 100
Time to get coefficients: 0.176 s
Stochastic Time: 4.614 s
83 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.635 s
84 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.615 s
85 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.679 s
86 of 100
Time to get coefficients: 0.176 s
Stochastic Time: 4.631 s
87 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.579 s
88 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.615 s
89 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.562 s
90 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.555 s
91 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.587 s
92 of 100
Time to get coefficients: 0.175 s
Stochastic Time: 4.603 s
93 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.621 s
94 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.641 s
95 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.598 s
96 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.623 s
97 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.626 s
98 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.590 s
99 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.626 s
Total Simulation Time: 492.396
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[1.48500062e-02+0.j 2.70001056e-04+0.j 2.70001056e-04+0.j ...
  2.70001056e-04+0.j 2.70001056e-04+0.j 4.26909153e-02+0.j]
 [2.70001056e-04+0.j 1.01485001e+00+0.j 2.70000000e-05+0.j ...
  2.70000000e-05+0.j 2.70000000e-05+0.j 4.26907484e-03+0.j]
 [2.70001056e-04+0.j 2.70000000e-05+0.j 1.01485001e+00+0.j ...
  2.70000000e-05+0.j 2.70000000e-05+0.j 4.26907484e-03+0.j]
 ...
 [2.70001056e-04+0.j 2.70000000e-05+0.j 2.70000000e-05+0.j ...
  1.01485001e+00+0.j 2.70000000e-05+0.j 4.26907484e-03+0.j]
 [2.70001056e-04+0.j 2.70000000e-05+0.j 2.70000000e-05+0.j ...
  2.70000000e-05+0.j 1.01485001e+00+0.j 4.26907484e-03+0.j]
 [4.26909153e-02+0.j 4.26907484e-03+0.j 4.26907484e-03+0.j ...
  4.26907484e-03+0.j 4.26907484e-03+0.j 1.36485001e+00+0.j]]
Eigs:
 [0.01348337+0.00000000e+00j 0.99287677+0.00000000e+00j
 1.01482301+0.00000000e+00j ... 1.01482301-1.66627263e-20j
 1.01482301+0.00000000e+00j 1.41516289+0.00000000e+00j]
0 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 12.613 s
1 of 100
Time to get coefficients: 0.175 s
Stochastic Time: 4.731 s
2 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.759 s
3 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.721 s
4 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.709 s
5 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.712 s
6 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.723 s
7 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.738 s
8 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.709 s
9 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.725 s
10 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.721 s
11 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.725 s
12 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.726 s
13 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.729 s
14 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.723 s
15 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.708 s
16 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.718 s
17 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.717 s
18 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.715 s
19 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.700 s
20 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.736 s
21 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.725 s
22 of 100
Time to get coefficients: 0.175 s
Stochastic Time: 4.711 s
23 of 100
Time to get coefficients: 0.175 s
Stochastic Time: 4.715 s
24 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.730 s
25 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.709 s
26 of 100
Time to get coefficients: 0.175 s
Stochastic Time: 4.747 s
27 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.721 s
28 of 100
Time to get coefficients: 0.174 s
Stochastic Time: 4.712 s
29 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.713 s
30 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.734 s
31 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.796 s
32 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.743 s
33 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.715 s
34 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.693 s
35 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.693 s
36 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.745 s
37 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.734 s
38 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.706 s
39 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.696 s
40 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.714 s
41 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.713 s
42 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.716 s
43 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.717 s
44 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.679 s
45 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.673 s
46 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.687 s
47 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.673 s
48 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.694 s
49 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.668 s
50 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.687 s
51 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.689 s
52 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.664 s
53 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.675 s
54 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.645 s
55 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.682 s
56 of 100
Time to get coefficients: 0.170 s
Stochastic Time: 4.685 s
57 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.670 s
58 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.665 s
59 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.648 s
60 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.645 s
61 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.619 s
62 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.609 s
63 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.638 s
64 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.618 s
65 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.610 s
66 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.576 s
67 of 100
Time to get coefficients: 0.166 s
Stochastic Time: 4.564 s
68 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.578 s
69 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.610 s
70 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.598 s
71 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.618 s
72 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.639 s
73 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.652 s
74 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.599 s
75 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.579 s
76 of 100
Time to get coefficients: 0.171 s
Stochastic Time: 4.514 s
77 of 100
Time to get coefficients: 0.166 s
Stochastic Time: 4.556 s
78 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.568 s
79 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.580 s
80 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.606 s
81 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.590 s
82 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.613 s
83 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.617 s
84 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.613 s
85 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.650 s
86 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.634 s
87 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.588 s
88 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.594 s
89 of 100
Time to get coefficients: 0.172 s
Stochastic Time: 4.568 s
90 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.580 s
91 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.588 s
92 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.626 s
93 of 100
Time to get coefficients: 0.173 s
Stochastic Time: 4.611 s
94 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.626 s
95 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.574 s
96 of 100
Time to get coefficients: 0.167 s
Stochastic Time: 4.612 s
97 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.600 s
98 of 100
Time to get coefficients: 0.169 s
Stochastic Time: 4.593 s
99 of 100
Time to get coefficients: 0.168 s
Stochastic Time: 4.620 s
Total Simulation Time: 492.462
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[1.37500057e-02+0.j 2.50000978e-04+0.j 2.50000978e-04+0.j ...
  2.50000978e-04+0.j 2.50000978e-04+0.j 3.95286253e-02+0.j]
 [2.50000978e-04+0.j 1.01375001e+00+0.j 2.50000000e-05+0.j ...
  2.50000000e-05+0.j 2.50000000e-05+0.j 3.95284708e-03+0.j]
 [2.50000978e-04+0.j 2.50000000e-05+0.j 1.01375001e+00+0.j ...
  2.50000000e-05+0.j 2.50000000e-05+0.j 3.95284708e-03+0.j]
 ...
 [2.50000978e-04+0.j 2.50000000e-05+0.j 2.50000000e-05+0.j ...
  1.01375001e+00+0.j 2.50000000e-05+0.j 3.95284708e-03+0.j]
 [2.50000978e-04+0.j 2.50000000e-05+0.j 2.50000000e-05+0.j ...
  2.50000000e-05+0.j 1.01375001e+00+0.j 3.95284708e-03+0.j]
 [3.95286253e-02+0.j 3.95284708e-03+0.j 3.95284708e-03+0.j ...
  3.95284708e-03+0.j 3.95284708e-03+0.j 1.26375001e+00+0.j]]
Eigs:
 [0.01248581-5.32905553e-38j 0.98313942-2.38168082e-34j
 1.01372501-1.08420217e-19j ... 1.01372501-1.73133534e-17j
 1.01372501-1.23158591e-18j 1.32059979-2.70794945e-36j]
0 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 14.296 s
1 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.867 s
2 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.867 s
3 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.868 s
4 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.867 s
5 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.869 s
6 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.872 s
7 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.868 s
8 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.867 s
9 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.867 s
10 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.867 s
11 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.867 s
12 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.875 s
13 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.868 s
14 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.866 s
15 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.868 s
16 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.865 s
17 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.867 s
18 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.871 s
19 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.863 s
20 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.867 s
21 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.865 s
22 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.867 s
23 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.864 s
24 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.874 s
25 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.867 s
26 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.864 s
27 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.866 s
28 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.865 s
29 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.858 s
30 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.872 s
31 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.864 s
32 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.865 s
33 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.864 s
34 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.865 s
35 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.865 s
36 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.873 s
37 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.863 s
38 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.887 s
39 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.850 s
40 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.838 s
41 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.849 s
42 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.855 s
43 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.852 s
44 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.847 s
45 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.849 s
46 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.842 s
47 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.855 s
48 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.859 s
49 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.849 s
50 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.853 s
51 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.843 s
52 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.836 s
53 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.853 s
54 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.863 s
55 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.856 s
56 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.847 s
57 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.849 s
58 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.847 s
59 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.850 s
60 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.862 s
61 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.847 s
62 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.844 s
63 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.838 s
64 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.833 s
65 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.848 s
66 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.855 s
67 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.836 s
68 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.844 s
69 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.836 s
70 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.835 s
71 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.828 s
72 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.853 s
73 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.842 s
74 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.824 s
75 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.824 s
76 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.827 s
77 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.841 s
78 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.831 s
79 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.834 s
80 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.837 s
81 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.830 s
82 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.879 s
83 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.841 s
84 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.861 s
85 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.836 s
86 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.846 s
87 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.823 s
88 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.837 s
89 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.845 s
90 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.838 s
91 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.844 s
92 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.850 s
93 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.852 s
94 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.858 s
95 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.857 s
96 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.856 s
97 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.849 s
98 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.843 s
99 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.850 s
Total Simulation Time: 513.945
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[5.28000221e-02+0.j 9.60003754e-04+0.j 9.60003754e-04+0.j ...
  9.60003754e-04+0.j 9.60003754e-04+0.j 7.58949606e-02+0.j]
 [9.60003754e-04+0.j 1.05280002e+00+0.j 9.60000000e-05+0.j ...
  9.60000000e-05+0.j 9.60000000e-05+0.j 7.58946638e-03+0.j]
 [9.60003754e-04+0.j 9.60000000e-05+0.j 1.05280002e+00+0.j ...
  9.60000000e-05+0.j 9.60000000e-05+0.j 7.58946638e-03+0.j]
 ...
 [9.60003754e-04+0.j 9.60000000e-05+0.j 9.60000000e-05+0.j ...
  1.05280002e+00+0.j 9.60000000e-05+0.j 7.58946638e-03+0.j]
 [9.60003754e-04+0.j 9.60000000e-05+0.j 9.60000000e-05+0.j ...
  9.60000000e-05+0.j 1.05280002e+00+0.j 7.58946638e-03+0.j]
 [7.58949606e-02+0.j 7.58946638e-03+0.j 7.58946638e-03+0.j ...
  7.58946638e-03+0.j 7.58946638e-03+0.j 1.25280002e+00+0.j]]
Eigs:
 [0.0477993 +0.00000000e+00j 0.95580278+0.00000000e+00j
 1.05270402-1.40946282e-18j ... 1.05270402-2.51534904e-17j
 1.05270402+8.35513299e-18j 1.45070198+0.00000000e+00j]
0 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 14.274 s
1 of 100
Time to get coefficients: 0.189 s
Stochastic Time: 4.909 s
2 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.912 s
3 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.909 s
4 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.909 s
5 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.914 s
6 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.915 s
7 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.909 s
8 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.910 s
9 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.911 s
10 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.910 s
11 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.910 s
12 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.918 s
13 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.909 s
14 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.912 s
15 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.910 s
16 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.908 s
17 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.910 s
18 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.916 s
19 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.908 s
20 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.909 s
21 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.908 s
22 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.910 s
23 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.908 s
24 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.916 s
25 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.910 s
26 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.907 s
27 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.908 s
28 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.909 s
29 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.903 s
30 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.911 s
31 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.913 s
32 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.901 s
33 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.888 s
34 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.895 s
35 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.883 s
36 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.889 s
37 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.877 s
38 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.881 s
39 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.893 s
40 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.882 s
41 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.874 s
42 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.876 s
43 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.873 s
44 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.882 s
45 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.888 s
46 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.892 s
47 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.882 s
48 of 100
Time to get coefficients: 0.189 s
Stochastic Time: 4.874 s
49 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.871 s
50 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.879 s
51 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.874 s
52 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.882 s
53 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.894 s
54 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.886 s
55 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.882 s
56 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.877 s
57 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.874 s
58 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.875 s
59 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.886 s
60 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.877 s
61 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.874 s
62 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.861 s
63 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.870 s
64 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.859 s
65 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.882 s
66 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.822 s
67 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.844 s
68 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.852 s
69 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.832 s
70 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.826 s
71 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.835 s
72 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.833 s
73 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.849 s
74 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.835 s
75 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.861 s
76 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.836 s
77 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.847 s
78 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.822 s
79 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.859 s
80 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.837 s
81 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.840 s
82 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.828 s
83 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.881 s
84 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.844 s
85 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.867 s
86 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.845 s
87 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.857 s
88 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.863 s
89 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.870 s
90 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.855 s
91 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.841 s
92 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.847 s
93 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.850 s
94 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.939 s
95 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.933 s
96 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.843 s
97 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.840 s
98 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.859 s
99 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.852 s
Total Simulation Time: 516.497
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[5.06000211e-02+0.j 9.20003597e-04+0.j 9.20003597e-04+0.j ...
  9.20003597e-04+0.j 9.20003597e-04+0.j 7.27326706e-02+0.j]
 [9.20003597e-04+0.j 1.05060002e+00+0.j 9.20000000e-05+0.j ...
  9.20000000e-05+0.j 9.20000000e-05+0.j 7.27323862e-03+0.j]
 [9.20003597e-04+0.j 9.20000000e-05+0.j 1.05060002e+00+0.j ...
  9.20000000e-05+0.j 9.20000000e-05+0.j 7.27323862e-03+0.j]
 ...
 [9.20003597e-04+0.j 9.20000000e-05+0.j 9.20000000e-05+0.j ...
  1.05060002e+00+0.j 9.20000000e-05+0.j 7.27323862e-03+0.j]
 [9.20003597e-04+0.j 9.20000000e-05+0.j 9.20000000e-05+0.j ...
  9.20000000e-05+0.j 1.05060002e+00+0.j 7.27323862e-03+0.j]
 [7.27326706e-02+0.j 7.27323862e-03+0.j 7.27323862e-03+0.j ...
  7.27323862e-03+0.j 7.27323862e-03+0.j 1.20060002e+00+0.j]]
Eigs:
 [0.04581601-1.45145614e-36j 0.94049303+4.79353563e-34j
 1.05050802-1.05879118e-22j ... 1.05050802-1.64798730e-17j
 1.05050802-1.59106704e-20j 1.40739902-8.97068520e-35j]
0 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 14.418 s
1 of 100
Time to get coefficients: 0.188 s
Stochastic Time: 4.915 s
2 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.914 s
3 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.913 s
4 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.913 s
5 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.918 s
6 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.920 s
7 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.915 s
8 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.912 s
9 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.915 s
10 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.915 s
11 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.913 s
12 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.921 s
13 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.913 s
14 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.916 s
15 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.914 s
16 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.919 s
17 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.921 s
18 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.926 s
19 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.919 s
20 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.920 s
21 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.919 s
22 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.921 s
23 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.919 s
24 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.924 s
25 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.919 s
26 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.918 s
27 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.918 s
28 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.919 s
29 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.914 s
30 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.926 s
31 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.919 s
32 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.915 s
33 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.900 s
34 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.872 s
35 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.885 s
36 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.871 s
37 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.869 s
38 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.874 s
39 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.885 s
40 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.878 s
41 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.884 s
42 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.890 s
43 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.882 s
44 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.885 s
45 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.876 s
46 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.869 s
47 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.882 s
48 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.885 s
49 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.875 s
50 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.872 s
51 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.882 s
52 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.886 s
53 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.897 s
54 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.885 s
55 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.871 s
56 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.886 s
57 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.872 s
58 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.882 s
59 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.892 s
60 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.885 s
61 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.882 s
62 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.875 s
63 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.868 s
64 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.862 s
65 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.888 s
66 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.889 s
67 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.870 s
68 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.864 s
69 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.878 s
70 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.879 s
71 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.882 s
72 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.875 s
73 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.870 s
74 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.835 s
75 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.870 s
76 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.847 s
77 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.860 s
78 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.845 s
79 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.841 s
80 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.843 s
81 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.834 s
82 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.847 s
83 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.850 s
84 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.871 s
85 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.875 s
86 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.839 s
87 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.838 s
88 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.832 s
89 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.881 s
90 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.847 s
91 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.837 s
92 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.849 s
93 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.853 s
94 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.876 s
95 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.870 s
96 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.841 s
97 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.831 s
98 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.849 s
99 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.871 s
Total Simulation Time: 517.137
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[1.32000055e-02+0.j 2.40000938e-04+0.j 2.40000938e-04+0.j ...
  2.40000938e-04+0.j 2.40000938e-04+0.j 3.79474803e-02+0.j]
 [2.40000938e-04+0.j 1.01320001e+00+0.j 2.40000000e-05+0.j ...
  2.40000000e-05+0.j 2.40000000e-05+0.j 3.79473319e-03+0.j]
 [2.40000938e-04+0.j 2.40000000e-05+0.j 1.01320001e+00+0.j ...
  2.40000000e-05+0.j 2.40000000e-05+0.j 3.79473319e-03+0.j]
 ...
 [2.40000938e-04+0.j 2.40000000e-05+0.j 2.40000000e-05+0.j ...
  1.01320001e+00+0.j 2.40000000e-05+0.j 3.79473319e-03+0.j]
 [2.40000938e-04+0.j 2.40000000e-05+0.j 2.40000000e-05+0.j ...
  2.40000000e-05+0.j 1.01320001e+00+0.j 3.79473319e-03+0.j]
 [3.79474803e-02+0.j 3.79473319e-03+0.j 3.79473319e-03+0.j ...
  3.79473319e-03+0.j 3.79473319e-03+0.j 1.21320001e+00+0.j]]
Eigs:
 [0.01198697+0.00000000e+00j 0.97648366+0.00000000e+00j
 1.01317601+3.43353275e-17j ... 1.01317601-7.12049777e-17j
 1.01317601-9.39867758e-18j 1.27510539+0.00000000e+00j]
0 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 14.441 s
1 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.954 s
2 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.954 s
3 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.953 s
4 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.956 s
5 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.957 s
6 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.960 s
7 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.952 s
8 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.952 s
9 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.954 s
10 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.957 s
11 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.951 s
12 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.956 s
13 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.954 s
14 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.955 s
15 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.952 s
16 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.982 s
17 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.984 s
18 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.988 s
19 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.982 s
20 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.981 s
21 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.981 s
22 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.983 s
23 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.984 s
24 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.988 s
25 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.980 s
26 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.984 s
27 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.981 s
28 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.977 s
29 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.949 s
30 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.966 s
31 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.946 s
32 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.938 s
33 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.944 s
34 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.945 s
35 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.949 s
36 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.952 s
37 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.950 s
38 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.948 s
39 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.952 s
40 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.941 s
41 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.953 s
42 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.947 s
43 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.941 s
44 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.947 s
45 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.944 s
46 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.948 s
47 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.947 s
48 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.944 s
49 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.948 s
50 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.944 s
51 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.933 s
52 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.938 s
53 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.943 s
54 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.946 s
55 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.948 s
56 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.933 s
57 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.932 s
58 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.922 s
59 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.912 s
60 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.911 s
61 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.905 s
62 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.890 s
63 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.886 s
64 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.883 s
65 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.871 s
66 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.885 s
67 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.864 s
68 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.866 s
69 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.852 s
70 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.856 s
71 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.839 s
72 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.837 s
73 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.817 s
74 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.845 s
75 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.833 s
76 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.846 s
77 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.831 s
78 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.847 s
79 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.842 s
80 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.845 s
81 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.843 s
82 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.869 s
83 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.843 s
84 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.833 s
85 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.826 s
86 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.842 s
87 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.824 s
88 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.846 s
89 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.855 s
90 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.842 s
91 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.856 s
92 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.857 s
93 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.853 s
94 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.876 s
95 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.863 s
96 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.886 s
97 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.841 s
98 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.835 s
99 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.867 s
Total Simulation Time: 520.202
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[5.50000230e-02+0.j 1.00000391e-03+0.j 1.00000391e-03+0.j ...
  1.00000391e-03+0.j 1.00000391e-03+0.j 7.90572506e-02+0.j]
 [1.00000391e-03+0.j 1.05500002e+00+0.j 1.00000000e-04+0.j ...
  1.00000000e-04+0.j 1.00000000e-04+0.j 7.90569415e-03+0.j]
 [1.00000391e-03+0.j 1.00000000e-04+0.j 1.05500002e+00+0.j ...
  1.00000000e-04+0.j 1.00000000e-04+0.j 7.90569415e-03+0.j]
 ...
 [1.00000391e-03+0.j 1.00000000e-04+0.j 1.00000000e-04+0.j ...
  1.05500002e+00+0.j 1.00000000e-04+0.j 7.90569415e-03+0.j]
 [1.00000391e-03+0.j 1.00000000e-04+0.j 1.00000000e-04+0.j ...
  1.00000000e-04+0.j 1.05500002e+00+0.j 7.90569415e-03+0.j]
 [7.90572506e-02+0.j 7.90569415e-03+0.j 7.90569415e-03+0.j ...
  7.90569415e-03+0.j 7.90569415e-03+0.j 1.30500002e+00+0.j]]
Eigs:
 [0.0497819 -7.47094791e-35j 0.96944104+3.78443155e-33j
 1.05490002-6.93889390e-18j ... 1.05490002+4.43421748e-19j
 1.05490002+5.18892383e-18j 1.49567713-9.68010490e-33j]
0 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 14.334 s
1 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.982 s
2 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.982 s
3 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.983 s
4 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.982 s
5 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.983 s
6 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.988 s
7 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.982 s
8 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.983 s
9 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.983 s
10 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.983 s
11 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.981 s
12 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.987 s
13 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.981 s
14 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.984 s
15 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.980 s
16 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.982 s
17 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.984 s
18 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.988 s
19 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.981 s
20 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.982 s
21 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.983 s
22 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.982 s
23 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.983 s
24 of 100
Time to get coefficients: 0.188 s
Stochastic Time: 4.984 s
25 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.982 s
26 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.972 s
27 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.981 s
28 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.980 s
29 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.989 s
30 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.982 s
31 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.981 s
32 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.979 s
33 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.967 s
34 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.951 s
35 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.950 s
36 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.952 s
37 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.949 s
38 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.950 s
39 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.966 s
40 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.961 s
41 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.969 s
42 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.964 s
43 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.951 s
44 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.939 s
45 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.941 s
46 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.943 s
47 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.945 s
48 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.954 s
49 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.940 s
50 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.951 s
51 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.959 s
52 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.943 s
53 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.956 s
54 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.967 s
55 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.932 s
56 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.947 s
57 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.930 s
58 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.913 s
59 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.918 s
60 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.905 s
61 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.915 s
62 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.899 s
63 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.889 s
64 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.919 s
65 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.903 s
66 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.901 s
67 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.890 s
68 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.901 s
69 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.892 s
70 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.893 s
71 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.835 s
72 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.853 s
73 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.840 s
74 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.834 s
75 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.832 s
76 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.830 s
77 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.834 s
78 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.823 s
79 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.842 s
80 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.857 s
81 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.862 s
82 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.852 s
83 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.831 s
84 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.829 s
85 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.823 s
86 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.826 s
87 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.818 s
88 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.827 s
89 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.830 s
90 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.834 s
91 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.834 s
92 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.848 s
93 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.837 s
94 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.868 s
95 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.893 s
96 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.852 s
97 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.843 s
98 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.877 s
99 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.842 s
Total Simulation Time: 520.827
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[1.43000060e-02+0.j 2.60001017e-04+0.j 2.60001017e-04+0.j ...
  2.60001017e-04+0.j 2.60001017e-04+0.j 4.11097703e-02+0.j]
 [2.60001017e-04+0.j 1.01430001e+00+0.j 2.60000000e-05+0.j ...
  2.60000000e-05+0.j 2.60000000e-05+0.j 4.11096096e-03+0.j]
 [2.60001017e-04+0.j 2.60000000e-05+0.j 1.01430001e+00+0.j ...
  2.60000000e-05+0.j 2.60000000e-05+0.j 4.11096096e-03+0.j]
 ...
 [2.60001017e-04+0.j 2.60000000e-05+0.j 2.60000000e-05+0.j ...
  1.01430001e+00+0.j 2.60000000e-05+0.j 4.11096096e-03+0.j]
 [2.60001017e-04+0.j 2.60000000e-05+0.j 2.60000000e-05+0.j ...
  2.60000000e-05+0.j 1.01430001e+00+0.j 4.11096096e-03+0.j]
 [4.11097703e-02+0.j 4.11096096e-03+0.j 4.11096096e-03+0.j ...
  4.11096096e-03+0.j 4.11096096e-03+0.j 1.31430001e+00+0.j]]
Eigs:
 [0.01298461+8.66289894e-39j 0.98847414-6.60293350e-36j
 1.01427401-6.50521303e-19j ... 1.01427401-7.06899816e-17j
 1.01427401+5.20417043e-18j 1.36741527+5.99249410e-37j]
0 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 14.468 s
1 of 100
Time to get coefficients: 0.193 s
Stochastic Time: 4.994 s
2 of 100
Time to get coefficients: 0.190 s
Stochastic Time: 4.995 s
3 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.990 s
4 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.995 s
5 of 100
Time to get coefficients: 0.189 s
Stochastic Time: 4.997 s
6 of 100
Time to get coefficients: 0.188 s
Stochastic Time: 4.995 s
7 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.993 s
8 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.992 s
9 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.990 s
10 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.994 s
11 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.994 s
12 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.997 s
13 of 100
Time to get coefficients: 0.189 s
Stochastic Time: 4.992 s
14 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.991 s
15 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.991 s
16 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 5.007 s
17 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 5.003 s
18 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 5.009 s
19 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 5.005 s
20 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 5.000 s
21 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 5.005 s
22 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 5.008 s
23 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 5.011 s
24 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 5.003 s
25 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 5.004 s
26 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 5.004 s
27 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 5.006 s
28 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 5.000 s
29 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 5.011 s
30 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 5.007 s
31 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 5.007 s
32 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 5.002 s
33 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 5.005 s
34 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.984 s
35 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.967 s
36 of 100
Time to get coefficients: 0.189 s
Stochastic Time: 4.988 s
37 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.977 s
38 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.973 s
39 of 100
Time to get coefficients: 0.188 s
Stochastic Time: 4.982 s
40 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.978 s
41 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.979 s
42 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.964 s
43 of 100
Time to get coefficients: 0.188 s
Stochastic Time: 4.961 s
44 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.968 s
45 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.978 s
46 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.978 s
47 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.966 s
48 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.964 s
49 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.980 s
50 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.963 s
51 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.994 s
52 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.974 s
53 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.964 s
54 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.966 s
55 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.960 s
56 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.962 s
57 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.965 s
58 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.963 s
59 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.940 s
60 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.941 s
61 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.919 s
62 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.913 s
63 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.925 s
64 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.925 s
65 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.907 s
66 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.906 s
67 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.906 s
68 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.898 s
69 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.885 s
70 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.859 s
71 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.863 s
72 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.863 s
73 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.845 s
74 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.870 s
75 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.880 s
76 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.876 s
77 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.867 s
78 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.869 s
79 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.861 s
80 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.848 s
81 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.851 s
82 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.918 s
83 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.876 s
84 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.854 s
85 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.856 s
86 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.873 s
87 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.865 s
88 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.870 s
89 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.885 s
90 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.858 s
91 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.848 s
92 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.861 s
93 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.881 s
94 of 100
Time to get coefficients: 0.187 s
Stochastic Time: 4.866 s
95 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.878 s
96 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.863 s
97 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.871 s
98 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.877 s
99 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.862 s
Total Simulation Time: 523.479
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[6.16000257e-02+0.j 1.12000438e-03+0.j 1.12000438e-03+0.j ...
  1.12000438e-03+0.j 1.12000438e-03+0.j 8.85441207e-02+0.j]
 [1.12000438e-03+0.j 1.06160003e+00+0.j 1.12000000e-04+0.j ...
  1.12000000e-04+0.j 1.12000000e-04+0.j 8.85437745e-03+0.j]
 [1.12000438e-03+0.j 1.12000000e-04+0.j 1.06160003e+00+0.j ...
  1.12000000e-04+0.j 1.12000000e-04+0.j 8.85437745e-03+0.j]
 ...
 [1.12000438e-03+0.j 1.12000000e-04+0.j 1.12000000e-04+0.j ...
  1.06160003e+00+0.j 1.12000000e-04+0.j 8.85437745e-03+0.j]
 [1.12000438e-03+0.j 1.12000000e-04+0.j 1.12000000e-04+0.j ...
  1.12000000e-04+0.j 1.06160003e+00+0.j 8.85437745e-03+0.j]
 [8.85441207e-02+0.j 8.85437745e-03+0.j 8.85437745e-03+0.j ...
  8.85437745e-03+0.j 8.85437745e-03+0.j 1.46160003e+00+0.j]]
Eigs:
 [0.05572561+6.90739172e-34j 1.0029237 +5.54734367e-31j
 1.06148803-3.46944695e-18j ... 1.06148803-1.38777878e-17j
 1.06148803+1.30104261e-18j 1.63803877+3.31390851e-32j]
0 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 13.428 s
1 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.839 s
2 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.829 s
3 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.829 s
4 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.831 s
5 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.831 s
6 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.836 s
7 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.838 s
8 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.830 s
9 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.831 s
10 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.836 s
11 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.829 s
12 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.836 s
13 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.852 s
14 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.829 s
15 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.830 s
16 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.839 s
17 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.840 s
18 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.843 s
19 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.856 s
20 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.849 s
21 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.846 s
22 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.840 s
23 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.842 s
24 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.841 s
25 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.846 s
26 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.838 s
27 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.837 s
28 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.825 s
29 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.810 s
30 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.807 s
31 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.867 s
32 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.809 s
33 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.827 s
34 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.817 s
35 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.800 s
36 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.825 s
37 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.839 s
38 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.818 s
39 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.821 s
40 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.829 s
41 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.826 s
42 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.813 s
43 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.831 s
44 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.816 s
45 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.820 s
46 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.832 s
47 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.817 s
48 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.808 s
49 of 100
Time to get coefficients: 0.185 s
Stochastic Time: 4.834 s
50 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.825 s
51 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.819 s
52 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.821 s
53 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.827 s
54 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.824 s
55 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.837 s
56 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.817 s
57 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.860 s
58 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.835 s
59 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.854 s
60 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.839 s
61 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.814 s
62 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.822 s
63 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.818 s
64 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.835 s
65 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.811 s
66 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.819 s
67 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.844 s
68 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.821 s
69 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.820 s
70 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.811 s
71 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.812 s
72 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.816 s
73 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.823 s
74 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.835 s
75 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.805 s
76 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.810 s
77 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.826 s
78 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.874 s
79 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.829 s
80 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.820 s
81 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.811 s
82 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.857 s
83 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.837 s
84 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.815 s
85 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.859 s
86 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.822 s
87 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.830 s
88 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.818 s
89 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.824 s
90 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.841 s
91 of 100
Time to get coefficients: 0.195 s
Stochastic Time: 4.832 s
92 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.824 s
93 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.848 s
94 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.860 s
95 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.829 s
96 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.838 s
97 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.836 s
98 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.822 s
99 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.840 s
Total Simulation Time: 510.514
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[6.60000276e-02+0.j 1.20000469e-03+0.j 1.20000469e-03+0.j ...
  1.20000469e-03+0.j 1.20000469e-03+0.j 9.48687007e-02+0.j]
 [1.20000469e-03+0.j 1.06600003e+00+0.j 1.20000000e-04+0.j ...
  1.20000000e-04+0.j 1.20000000e-04+0.j 9.48683298e-03+0.j]
 [1.20000469e-03+0.j 1.20000000e-04+0.j 1.06600003e+00+0.j ...
  1.20000000e-04+0.j 1.20000000e-04+0.j 9.48683298e-03+0.j]
 ...
 [1.20000469e-03+0.j 1.20000000e-04+0.j 1.20000000e-04+0.j ...
  1.06600003e+00+0.j 1.20000000e-04+0.j 9.48683298e-03+0.j]
 [1.20000469e-03+0.j 1.20000000e-04+0.j 1.20000000e-04+0.j ...
  1.20000000e-04+0.j 1.06600003e+00+0.j 9.48683298e-03+0.j]
 [9.48687007e-02+0.j 9.48683298e-03+0.j 9.48683298e-03+0.j ...
  9.48683298e-03+0.j 9.48683298e-03+0.j 1.56600003e+00+0.j]]
Eigs:
 [0.05968473+5.90546416e-38j 1.02096319-1.76999024e-35j
 1.06588003+5.42101086e-18j ... 1.06588003-5.96833973e-19j
 1.06588003-5.75982404e-20j 1.73723216-2.26666403e-37j]
0 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 13.480 s
1 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.893 s
2 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.889 s
3 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.886 s
4 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.887 s
5 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.888 s
6 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.887 s
7 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.893 s
8 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.888 s
9 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.888 s
10 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.885 s
11 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.889 s
12 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.886 s
13 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.895 s
14 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.886 s
15 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.887 s
16 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.880 s
17 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.879 s
18 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.887 s
19 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.880 s
20 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.882 s
21 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.880 s
22 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.880 s
23 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.879 s
24 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.884 s
25 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.879 s
26 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.879 s
27 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.878 s
28 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.880 s
29 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.881 s
30 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.882 s
31 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.855 s
32 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.856 s
33 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.859 s
34 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.846 s
35 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.845 s
36 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.857 s
37 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.856 s
38 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.859 s
39 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.859 s
40 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.851 s
41 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.860 s
42 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.853 s
43 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.847 s
44 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.873 s
45 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.857 s
46 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.853 s
47 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.849 s
48 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.862 s
49 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.844 s
50 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.845 s
51 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.865 s
52 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.849 s
53 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.855 s
54 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.860 s
55 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.858 s
56 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.847 s
57 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.844 s
58 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.848 s
59 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.849 s
60 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.856 s
61 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.851 s
62 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.858 s
63 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.854 s
64 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.850 s
65 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.853 s
66 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.856 s
67 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.848 s
68 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.849 s
69 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.848 s
70 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.855 s
71 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.858 s
72 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.858 s
73 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.851 s
74 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.848 s
75 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.856 s
76 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.822 s
77 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.836 s
78 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.838 s
79 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.830 s
80 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.819 s
81 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.882 s
82 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.829 s
83 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.833 s
84 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.849 s
85 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.827 s
86 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.850 s
87 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.805 s
88 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.805 s
89 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.823 s
90 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.817 s
91 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.844 s
92 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.855 s
93 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.831 s
94 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.895 s
95 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.851 s
96 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.859 s
97 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.838 s
98 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.828 s
99 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.821 s
Total Simulation Time: 513.312
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[6.38000266e-02+0.j 1.16000454e-03+0.j 1.16000454e-03+0.j ...
  1.16000454e-03+0.j 1.16000454e-03+0.j 9.17064107e-02+0.j]
 [1.16000454e-03+0.j 1.06380003e+00+0.j 1.16000000e-04+0.j ...
  1.16000000e-04+0.j 1.16000000e-04+0.j 9.17060521e-03+0.j]
 [1.16000454e-03+0.j 1.16000000e-04+0.j 1.06380003e+00+0.j ...
  1.16000000e-04+0.j 1.16000000e-04+0.j 9.17060521e-03+0.j]
 ...
 [1.16000454e-03+0.j 1.16000000e-04+0.j 1.16000000e-04+0.j ...
  1.06380003e+00+0.j 1.16000000e-04+0.j 9.17060521e-03+0.j]
 [1.16000454e-03+0.j 1.16000000e-04+0.j 1.16000000e-04+0.j ...
  1.16000000e-04+0.j 1.06380003e+00+0.j 9.17060521e-03+0.j]
 [9.17064107e-02+0.j 9.17060521e-03+0.j 9.17060521e-03+0.j ...
  9.17060521e-03+0.j 9.17060521e-03+0.j 1.51380003e+00+0.j]]
Eigs:
 [0.0577055 +0.00000000e+00j 1.01227296+0.00000000e+00j
 1.06368403+1.99238412e-15j ... 1.06368403-7.58941521e-18j
 1.06368403+0.00000000e+00j 1.68730562+0.00000000e+00j]
0 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 13.563 s
1 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.894 s
2 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.885 s
3 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.882 s
4 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.887 s
5 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.887 s
6 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.894 s
7 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.885 s
8 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.886 s
9 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.887 s
10 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.885 s
11 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.886 s
12 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.892 s
13 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.888 s
14 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.886 s
15 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.887 s
16 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.885 s
17 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.882 s
18 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.889 s
19 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.881 s
20 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.882 s
21 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.883 s
22 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.881 s
23 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.882 s
24 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.889 s
25 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.883 s
26 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.881 s
27 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.883 s
28 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.881 s
29 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.882 s
30 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.887 s
31 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.878 s
32 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.874 s
33 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.873 s
34 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.875 s
35 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.854 s
36 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.853 s
37 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.851 s
38 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.854 s
39 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.851 s
40 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.846 s
41 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.853 s
42 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.874 s
43 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.851 s
44 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.862 s
45 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.856 s
46 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.856 s
47 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.844 s
48 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.859 s
49 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.860 s
50 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.858 s
51 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.857 s
52 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.858 s
53 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.857 s
54 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.856 s
55 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.860 s
56 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.899 s
57 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.866 s
58 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.868 s
59 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.852 s
60 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.863 s
61 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.852 s
62 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.860 s
63 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.854 s
64 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.856 s
65 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.861 s
66 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.856 s
67 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.851 s
68 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.877 s
69 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.861 s
70 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.855 s
71 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.854 s
72 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.860 s
73 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.844 s
74 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.861 s
75 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.862 s
76 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.853 s
77 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.854 s
78 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.858 s
79 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.811 s
80 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.819 s
81 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.818 s
82 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.819 s
83 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.840 s
84 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.836 s
85 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.824 s
86 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.813 s
87 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.820 s
88 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.831 s
89 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.831 s
90 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.815 s
91 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.816 s
92 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.828 s
93 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.797 s
94 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.852 s
95 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.825 s
96 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.834 s
97 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.821 s
98 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.818 s
99 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.853 s
Total Simulation Time: 513.481
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[1.65000069e-02+0.j 3.00001173e-04+0.j 3.00001173e-04+0.j ...
  3.00001173e-04+0.j 3.00001173e-04+0.j 4.74343504e-02+0.j]
 [3.00001173e-04+0.j 1.01650001e+00+0.j 3.00000000e-05+0.j ...
  3.00000000e-05+0.j 3.00000000e-05+0.j 4.74341649e-03+0.j]
 [3.00001173e-04+0.j 3.00000000e-05+0.j 1.01650001e+00+0.j ...
  3.00000000e-05+0.j 3.00000000e-05+0.j 4.74341649e-03+0.j]
 ...
 [3.00001173e-04+0.j 3.00000000e-05+0.j 3.00000000e-05+0.j ...
  1.01650001e+00+0.j 3.00000000e-05+0.j 4.74341649e-03+0.j]
 [3.00001173e-04+0.j 3.00000000e-05+0.j 3.00000000e-05+0.j ...
  3.00000000e-05+0.j 1.01650001e+00+0.j 4.74341649e-03+0.j]
 [4.74343504e-02+0.j 4.74341649e-03+0.j 4.74341649e-03+0.j ...
  4.74341649e-03+0.j 4.74341649e-03+0.j 1.51650001e+00+0.j]]
Eigs:
 [0.01497933+0.00000000e+00j 1.00269802+0.00000000e+00j
 1.01647001+0.00000000e+00j ... 1.01647001+1.91768259e-17j
 1.01647001+0.00000000e+00j 1.56179267+0.00000000e+00j]
0 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 13.651 s
1 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.923 s
2 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.923 s
3 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.921 s
4 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.922 s
5 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.923 s
6 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.929 s
7 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.923 s
8 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.921 s
9 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.920 s
10 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.922 s
11 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.919 s
12 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.929 s
13 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.922 s
14 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.919 s
15 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.922 s
16 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.921 s
17 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.923 s
18 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.929 s
19 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.920 s
20 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.924 s
21 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.921 s
22 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.923 s
23 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.920 s
24 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.927 s
25 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.921 s
26 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.923 s
27 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.920 s
28 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.922 s
29 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.918 s
30 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.926 s
31 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.916 s
32 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.937 s
33 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.923 s
34 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.912 s
35 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.912 s
36 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.925 s
37 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.934 s
38 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.922 s
39 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.921 s
40 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.910 s
41 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.935 s
42 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.925 s
43 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.919 s
44 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.923 s
45 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.920 s
46 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.934 s
47 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.931 s
48 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.915 s
49 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.926 s
50 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.920 s
51 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.917 s
52 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.909 s
53 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.930 s
54 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.915 s
55 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.909 s
56 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.924 s
57 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.903 s
58 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.887 s
59 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.894 s
60 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.882 s
61 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.867 s
62 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.859 s
63 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.858 s
64 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.867 s
65 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.877 s
66 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.841 s
67 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.836 s
68 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.828 s
69 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.829 s
70 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.823 s
71 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.820 s
72 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.814 s
73 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.836 s
74 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.800 s
75 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.800 s
76 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.826 s
77 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.863 s
78 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.813 s
79 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.828 s
80 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.824 s
81 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.816 s
82 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.821 s
83 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.808 s
84 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.808 s
85 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.847 s
86 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.820 s
87 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.807 s
88 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.834 s
89 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.820 s
90 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.822 s
91 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.815 s
92 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.812 s
93 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.811 s
94 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.823 s
95 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.847 s
96 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.840 s
97 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.817 s
98 of 100
Time to get coefficients: 0.177 s
Stochastic Time: 4.809 s
99 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.845 s
Total Simulation Time: 516.037
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[1.59500067e-02+0.j 2.90001134e-04+0.j 2.90001134e-04+0.j ...
  2.90001134e-04+0.j 2.90001134e-04+0.j 4.58532054e-02+0.j]
 [2.90001134e-04+0.j 1.01595001e+00+0.j 2.90000000e-05+0.j ...
  2.90000000e-05+0.j 2.90000000e-05+0.j 4.58530261e-03+0.j]
 [2.90001134e-04+0.j 2.90000000e-05+0.j 1.01595001e+00+0.j ...
  2.90000000e-05+0.j 2.90000000e-05+0.j 4.58530261e-03+0.j]
 ...
 [2.90001134e-04+0.j 2.90000000e-05+0.j 2.90000000e-05+0.j ...
  1.01595001e+00+0.j 2.90000000e-05+0.j 4.58530261e-03+0.j]
 [2.90001134e-04+0.j 2.90000000e-05+0.j 2.90000000e-05+0.j ...
  2.90000000e-05+0.j 1.01595001e+00+0.j 4.58530261e-03+0.j]
 [4.58532054e-02+0.j 4.58530261e-03+0.j 4.58530261e-03+0.j ...
  4.58530261e-03+0.j 4.58530261e-03+0.j 1.46595001e+00+0.j]]
Eigs:
 [0.01448073+2.69129836e-40j 0.99983989-8.00486524e-38j
 1.01592101-7.31537854e-24j ... 1.01592101+4.60119216e-24j
 1.01592101-4.13590306e-25j 1.5125004 +5.64533066e-38j]
0 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 13.731 s
1 of 100
Time to get coefficients: 0.186 s
Stochastic Time: 4.950 s
2 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.950 s
3 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.949 s
4 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.949 s
5 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.949 s
6 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.954 s
7 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.947 s
8 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.950 s
9 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.947 s
10 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.949 s
11 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.948 s
12 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.952 s
13 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.950 s
14 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.951 s
15 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.947 s
16 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.958 s
17 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.959 s
18 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.964 s
19 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.960 s
20 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.960 s
21 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.956 s
22 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.957 s
23 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.958 s
24 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.965 s
25 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.959 s
26 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.956 s
27 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.956 s
28 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.959 s
29 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.956 s
30 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.962 s
31 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.959 s
32 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.958 s
33 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.976 s
34 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.949 s
35 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.965 s
36 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.955 s
37 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.940 s
38 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.931 s
39 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.942 s
40 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.945 s
41 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.945 s
42 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.956 s
43 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.955 s
44 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.957 s
45 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.964 s
46 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.953 s
47 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.953 s
48 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.942 s
49 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.946 s
50 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.937 s
51 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.943 s
52 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.950 s
53 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.950 s
54 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.964 s
55 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.971 s
56 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.957 s
57 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.953 s
58 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.943 s
59 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.952 s
60 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.942 s
61 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.934 s
62 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.925 s
63 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.905 s
64 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.911 s
65 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.905 s
66 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.912 s
67 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.902 s
68 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.887 s
69 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.889 s
70 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.873 s
71 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.874 s
72 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.875 s
73 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.874 s
74 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.904 s
75 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.851 s
76 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.858 s
77 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.859 s
78 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.858 s
79 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.860 s
80 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.847 s
81 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.840 s
82 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.852 s
83 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.907 s
84 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.888 s
85 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.857 s
86 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.831 s
87 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.848 s
88 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.854 s
89 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.812 s
90 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.828 s
91 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.841 s
92 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.825 s
93 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.851 s
94 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.847 s
95 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.852 s
96 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.855 s
97 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.848 s
98 of 100
Time to get coefficients: 0.178 s
Stochastic Time: 4.861 s
99 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.862 s
Total Simulation Time: 519.706
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/scratch/bweight/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
M [0.+0.j 1.+0.j 1.+0.j ... 1.+0.j 1.+0.j 0.+0.j]
P [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]
H:
 [[1.54000064e-02+0.j 2.80001095e-04+0.j 2.80001095e-04+0.j ...
  2.80001095e-04+0.j 2.80001095e-04+0.j 4.42720603e-02+0.j]
 [2.80001095e-04+0.j 1.01540001e+00+0.j 2.80000000e-05+0.j ...
  2.80000000e-05+0.j 2.80000000e-05+0.j 4.42718872e-03+0.j]
 [2.80001095e-04+0.j 2.80000000e-05+0.j 1.01540001e+00+0.j ...
  2.80000000e-05+0.j 2.80000000e-05+0.j 4.42718872e-03+0.j]
 ...
 [2.80001095e-04+0.j 2.80000000e-05+0.j 2.80000000e-05+0.j ...
  1.01540001e+00+0.j 2.80000000e-05+0.j 4.42718872e-03+0.j]
 [2.80001095e-04+0.j 2.80000000e-05+0.j 2.80000000e-05+0.j ...
  2.80000000e-05+0.j 1.01540001e+00+0.j 4.42718872e-03+0.j]
 [4.42720603e-02+0.j 4.42718872e-03+0.j 4.42718872e-03+0.j ...
  4.42718872e-03+0.j 4.42718872e-03+0.j 1.41540001e+00+0.j]]
Eigs:
 [0.01398207+0.00000000e+00j 0.99660673+0.00000000e+00j
 1.01537201+0.00000000e+00j ... 1.01537201+3.52594008e-20j
 1.01537201+0.00000000e+00j 1.46358322+0.00000000e+00j]
0 of 100
Time to get coefficients: 0.189 s
Stochastic Time: 14.484 s
1 of 100
Time to get coefficients: 0.200 s
Stochastic Time: 4.983 s
2 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.984 s
3 of 100
Time to get coefficients: 0.193 s
Stochastic Time: 4.983 s
4 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.978 s
5 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.980 s
6 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.988 s
7 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.983 s
8 of 100
Time to get coefficients: 0.192 s
Stochastic Time: 4.982 s
9 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.983 s
10 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.982 s
11 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.983 s
12 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.988 s
13 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.987 s
14 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.985 s
15 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.978 s
16 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.983 s
17 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.981 s
18 of 100
Time to get coefficients: 0.193 s
Stochastic Time: 4.988 s
19 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.984 s
20 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.980 s
21 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.984 s
22 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.980 s
23 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.988 s
24 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.985 s
25 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.979 s
26 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.978 s
27 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.980 s
28 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.986 s
29 of 100
Time to get coefficients: 0.194 s
Stochastic Time: 4.990 s
30 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.977 s
31 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.979 s
32 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 5.011 s
33 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.957 s
34 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.938 s
35 of 100
Time to get coefficients: 0.184 s
Stochastic Time: 4.992 s
36 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.952 s
37 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.947 s
38 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.946 s
39 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.979 s
40 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.963 s
41 of 100
Time to get coefficients: 0.192 s
Stochastic Time: 4.981 s
42 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.951 s
43 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.941 s
44 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.954 s
45 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.972 s
46 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.983 s
47 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.980 s
48 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.953 s
49 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.944 s
50 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.970 s
51 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.940 s
52 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.966 s
53 of 100
Time to get coefficients: 0.193 s
Stochastic Time: 4.976 s
54 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.945 s
55 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.939 s
56 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.938 s
57 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.917 s
58 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.922 s
59 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.928 s
60 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.892 s
61 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.891 s
62 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.869 s
63 of 100
Time to get coefficients: 0.179 s
Stochastic Time: 4.907 s
64 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.889 s
65 of 100
Time to get coefficients: 0.194 s
Stochastic Time: 4.877 s
66 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.878 s
67 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.848 s
68 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.915 s
69 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.906 s
70 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.845 s
71 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.906 s
72 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.879 s
73 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.868 s
74 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.844 s
75 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.875 s
76 of 100
Time to get coefficients: 0.193 s
Stochastic Time: 4.908 s
77 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.894 s
78 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.892 s
79 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.865 s
80 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.863 s
81 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.857 s
82 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.863 s
83 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.845 s
84 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.877 s
85 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.853 s
86 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.860 s
87 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.893 s
88 of 100
Time to get coefficients: 0.192 s
Stochastic Time: 4.863 s
89 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.865 s
90 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.850 s
91 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.857 s
92 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.861 s
93 of 100
Time to get coefficients: 0.183 s
Stochastic Time: 4.874 s
94 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.876 s
95 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.862 s
96 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.904 s
97 of 100
Time to get coefficients: 0.181 s
Stochastic Time: 4.896 s
98 of 100
Time to get coefficients: 0.182 s
Stochastic Time: 4.854 s
99 of 100
Time to get coefficients: 0.180 s
Stochastic Time: 4.868 s
Total Simulation Time: 522.105
